### ISSUE TITLE
Procurar erros no código existente até agora

### ISSUE THREAD

**Issue by lauraadalmolin** [schoolsupport/schoolsupport.github.io#14]

**Comment by viniciuscrizel** [comment]
Na seção de login, ao digitar qualquer matrícula contendo 8 dígitos, mesmo que não exista, o campo está sendo marcado como válido (cor verde), corrigir para que apenas valide caso a matrícula exista no banco de dados.

**Comment by viniciuscrizel** [comment]
está sendo aceito cadastros em branco, corrigir para que apenas quando todos campos forem preenchidos corretamente, o botão de cadastrar ser liberado.

**Comment by viniciuscrizel** [comment]
Não há limite de caracteres na senha, para um melhor gerenciamento, seria viável que fosse estipulado um limite.

**Comment by andrewmota** [comment]
Erro dos cadastros em branco está corrigido!

**Comment by andrewmota** [comment]
Limite de caracteres na senha está corrigido!

**Comment by lauraadalmolin** [comment]
Quando acharem erros, abram issues e quando forem corrigi-las ou quiserem que alguém as corrija, também abram issues. Abram issues para tudo, sempre. Ou me chamem que eu abro.

**Comment by viniciuscrizel** [comment]
Rota pós-cadastro de conteúdos com problemas.

**Comment by viniciuscrizel** [comment]
Problema na rota pós-cadastro corrigido!

**Comment by andrewmota** [comment]
De todos os erros acima foram criadas issues e logo após terminar de faze-lás, foram fechadas!
